// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlP3byoGvGsr12nyuugJw6u3ux8vPzlqc',
    appId: '1:196272608738:web:0c106959beeb97ece0d5bb',
    messagingSenderId: '196272608738',
    projectId: 'dims-must',
    authDomain: 'dims-must.firebaseapp.com',
    storageBucket: 'dims-must.firebasestorage.app',
    measurementId: 'G-VD5JDHRJ2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcb3Re_o5hto7Kri7cQroZ6gWqTsC_WUo',
    appId: '1:196272608738:android:400278b4601dbe42e0d5bb',
    messagingSenderId: '196272608738',
    projectId: 'dims-must',
    storageBucket: 'dims-must.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBE7gS0oq3nRRzApxyzHuq86vi17jIAM',
    appId: '1:196272608738:ios:b9cc213d76a63cfde0d5bb',
    messagingSenderId: '196272608738',
    projectId: 'dims-must',
    storageBucket: 'dims-must.firebasestorage.app',
    iosBundleId: 'com.example.dims',
  );
}
